version: "3"
  
networks:
  test-network:
    driver: bridge

services:

  discovery-server:
    container_name: discovery-server
    image: varindersingh6885/nagpbookingsystem_discovery-server
    networks:
      - test-network
    ports:
      - "8761:8761"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/


  api-gateway:
    container_name: api-gateway
    image: varindersingh6885/nagpbookingsystem_api-gatway
    depends_on:
      - discovery-server
      - booking-service
      - db-flights-service
      - flights-service
      - identity-service
    networks:
      - test-network
    ports:
      - "8001:8001"
    links:
      - discovery-server
      - flights-service
      - db-flights-service
      - booking-service
      - identity-service
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka 
      - SPRING_PROFILES_ACTIVE=docker

  db-flights-service:
    container_name: db-flights-service
    image: varindersingh6885/nagpbookingsystem_db-flights-service
    networks:
      - test-network
    depends_on:
      - discovery-server
    ports:
      - "7001:7001"
    links:
      - discovery-server
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka

  flights-service:
    container_name: flights-service
    image: varindersingh6885/nagpbookingsystem_flights-service
    networks:
      - test-network
    depends_on:
      - discovery-server
      - db-flights-service
    ports:
      - "7000:7000"
    links:
      - db-flights-service
      - discovery-server
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka

  identity-service:
    container_name: identity-service
    image: varindersingh6885/nagpbookingsystem_identity-service
    networks:
      - test-network
    ports:
      - "9001:9001"
    depends_on:
      - discovery-server
    links:
      - discovery-server
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka
    
  booking-service:
    container_name: booking-service
    image: varindersingh6885/nagpbookingsystem_booking-service
    networks:
      - test-network
    ports:
      - "6000:6000"
    depends_on:
      - discovery-server
    links:
      - discovery-server
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka

  booking-saga-orchestrator:
    container_name: booking-saga-orchestrator
    image: varindersingh6885/nagpbookingsystem_booking-saga-orchestrator
    networks:
      - test-network
    ports:
      - "6500:6500"
    depends_on:
      - discovery-server
      - flights-service
    links:
      - discovery-server
      - flights-service
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka