server:
  port: 8001

spring:
 cloud:
   gateway:
     routes:
       - id: flights-service
         uri: lb://FLIGHTS-SERVICE
         predicates:
           - Path=/flights/**
         filters:
           - AuthenticationFilter

       - id: hotels-service
         uri: lb://HOTELS-SERVICE
         predicates:
           - Path=/hotels/**
         filters:
           - AuthenticationFilter


       - id: booking-service
         uri: lb://BOOKING-SERVICE
         predicates:
           - Path=/booking/**
         filters:
           - AuthenticationFilter
           
       - id: payments-service
         uri: lb://PAYMENTs-SERVICE
         predicates:
           - Path=/payments/**
         filters:
           - AuthenticationFilter

       - id: identity-service
         uri: lb://IDENTITY-SERVICE
         predicates:
           - Path=/users/**

 application:
   name: api-gateway

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/